import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./../globals.css";

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={notoSans.className}>{children}</div>;
}
